AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: 'MyWebAppLaunchTemplate'
      LaunchTemplateData:
        InstanceType: 't3.micro'
        ImageId: 'ami-0e577819b2a6cc996'
        SecurityGroupIds:
          - !ImportValue MySecurityGroupId
        KeyName: 'mykeypair'
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: 'Name'
                Value: 'AutoScalingInstance'
        UserData: 
          Fn::Base64: !Sub |
            #!/bin/bash
            # Update packages
            sudo yum update -y

            # Install required packages
            sudo yum install httpd git python3 python3-pip tmux -y

            # Start Apache2 service
            sudo systemctl start httpd
            sudo systemctl enable httpd

            # Upgrade pip3
            python3 -m pip install --upgrade pip

            # Install Flask
            sudo python3 -m pip install flask

            # Clone the GitHub repository
            cd /home/ec2-user
            git clone https://github.com/Jaesung411/mini_project_2.git

            # Run Flask app in tmux
            cd /home/ec2-user/mini_project_2
            tmux new-session -d -s flask-app "sudo python3 app.py --host=0.0.0.0 --port=8080"


  MyAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier:
        - !ImportValue MyPublicSubnet1Id
        - !ImportValue MyPublicSubnet2Id
        - !ImportValue MyPublicSubnet3Id
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '5'
      DesiredCapacity: '3'
      TargetGroupARNs: 
        - !ImportValue MyTargetGroupArn  # 대상 그룹의 ARN 참조
      Tags:
        - Key: 'Name'
          Value: 'AutoScalingInstance'
          PropagateAtLaunch: true

Outputs:
  MyAutoScalingGroupId:
    Value: !Ref MyAutoScalingGroup
    Export:
      Name: MyAutoScalingGroupId