AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: 'MyWebAppLaunchTemplate'
      LaunchTemplateData:
        InstanceType: 't3.micro'
        ImageId: 'ami-0e577819b2a6cc996'
        SecurityGroupIds:
          - !ImportValue MySecurityGroupId
        KeyName: 'mykeypair'
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: 'Name'
                Value: 'AutoScalingInstance'
        UserData: 
          Fn::Base64: !Sub |
            #!/bin/bash
            # Update packages
            sudo yum update -y
            
            # Install Apache2
            sudo yum install httpd -y
            
            # Start Apache2 service
            sudo systemctl start httpd
            sudo systemctl enable httpd
            
            # Create a test HTML file (optional)
            echo "<html><body><h1>Apache is running!</h1></body></html>" > /var/www/html/index.html
           
            pip3 install flask
            sudo yum install git python3 python3-pip tmux -y

            cd /home/ec2-user/mini_project_2
            python3 app.py --host=0.0.0.0 --port=8080


  MyAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier:
        - !ImportValue MyPublicSubnet1Id
        - !ImportValue MyPublicSubnet2Id
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '5'
      DesiredCapacity: '2'
      TargetGroupARNs: 
        - !ImportValue MyTargetGroupArn  # 대상 그룹의 ARN 참조
      Tags:
        - Key: 'Name'
          Value: 'AutoScalingInstance'
          PropagateAtLaunch: true

Outputs:
  MyAutoScalingGroupId:
    Value: !Ref MyAutoScalingGroup
    Export:
      Name: MyAutoScalingGroupId