AWSTemplateFormatVersion: '2010-09-09'

Resources:
  NetworkStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://mini2projectjs.s3.ap-northeast-3.amazonaws.com/network-template.yaml'

  SecurityStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://mini2projectjs.s3.ap-northeast-3.amazonaws.com/security-template.yaml'
    DependsOn: NetworkStack 

  AutoScalingStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://mini2projectjs.s3.ap-northeast-3.amazonaws.com/autoscaling-template.yaml'
    DependsOn: 
      - NetworkStack 
      - SecurityStack
      - LoadBalancerStack

  LoadBalancerStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://mini2projectjs.s3.ap-northeast-3.amazonaws.com/loadbalancer-template.yaml'
    DependsOn: 
      - NetworkStack 
      - SecurityStack
      
